Homework3
antonborisov571/HT-ITIS.2.1-student pull request #3
Opened 2023-09-26 18:40 UTC by antonborisov571

2023-09-28 21:12 UTC, clonediff requested changes

2023-09-28 21:12 UTC, clonediff commented on Tests.CSharp/Homework3/ConcurrencyTests.cs
> +        Assert.True(sw.Elapsed.TotalMilliseconds >= delay * 2);
А где здесь используются именованные семафоры?

2023-09-29 05:59 UTC, antonborisov571 commented on Tests.CSharp/Homework3/ConcurrencyTests.cs
> +        Assert.True(sw.Elapsed.TotalMilliseconds >= delay * 2);
Они в Program.cs, я сделал именно в Program.cs, потому что название теста указывает на процессы, как раз этот метод запускает 2 процесса. Только в Program.cs всё что добавил закомментировано, чтобы тест c Mutex проходил.

2023-09-29 06:00 UTC, antonborisov571 commented on Tests.CSharp/Homework3/ConcurrencyTests.cs
> +        Assert.True(sw.Elapsed.TotalMilliseconds >= delay * 2);
> А где здесь используются именованные семафоры?

Они в Program.cs, я сделал именно в Program.cs, потому что название теста указывает на процессы, как раз этот метод запускает 2 процесса. Только в Program.cs всё что добавил закомментировано, чтобы тест c Mutex проходил

2023-09-29 06:30 UTC, clonediff approved these changes

2023-09-29 06:31 UTC, merged